name: Feature request【中文】
description: 为这个项目提出一个想法
title: "[Feature Request]:"
labels:
  - enhancement
assignees: kings1990
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查项
      description: 确保您遵守以下声明
      options:
        - label: 我查阅了[功能文档](https://api-buddy.com/en/guide/features/)并且没有发现该功能
          required: true

        - label: 我搜索了现有问题，没有其他人提出类似的功能
          required: true

        - label: 我认为 25% 以上的用户对此功能持积极态度
          required: true

  - type: textarea
    id: feature
    attributes:
      label: 描述功能
      description: 它的用途和原因
      placeholder: 清晰简洁地描述该功能是什么，以及它将增强或解决什么问题。否则会被驳回
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 其他描述
      placeholder: 在此处添加有关功能请求的任何其他上下文或屏幕截图